### ISSUE TITLE
ERB example code on front page is incorrect (uses curly quotes)

### ISSUE THREAD

**Issue by ariasuni** [haml/haml-site#21]
The example on the front page is:

```erb
<section class=”container”>
  <h1><%= post.title %></h1>
  <h2><%= post.subtitle %></h2>
  <div class=”content”>
    <%= post.content %>
  </div>
</section>
```

It uses U+201C and U+201D (`“` and `”`) that are changed by ERB and won’t in HTML documents; instead of U+0022 (ASCII apostrophe). It should be:

```erb
<section class="container">
  <h1><%= post.title %></h1>
  <h2><%= post.subtitle %></h2>
  <div class="content">
    <%= post.content %>
  </div>
</section>
```

**Comment by amatsuda** [comment]
@ariasuni Good catch! Just fixed and published the documentation.
Thank you for the perfect bug report!
