### ISSUE TITLE
Syntax highlighting in REFERENCE

### ISSUE THREAD

**Issue by Frigory33** [haml/haml-site#29]
Hello,

As you can see in the [Custom filters](https://haml.info/docs/yardoc/file.REFERENCE.html#custom-filters) section of the REFERENCE, syntax highlighting for Ruby code hasn’t worked at all.

Also, what about enabling syntax highlighting for HTML and Haml codes in the REFERENCE? [On Wikipedia](https://en.wikipedia.org/wiki/Haml), you can see they’re colored.

**Comment by amatsuda** [comment]
Fixed via haml/haml@e4f4cfb7e3111a42451d5f27fbd142993e7ed73c. Thanks!
